{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Week 1：八家目标公司招股说明书 PDF 下载\n",
        "\n",
        "本 Notebook 用于下载以下八家公司的正式招股说明书 PDF，并生成下载日志：\n",
        "\n",
        "- 三联锻造\n",
        "- 友升股份\n",
        "- 黄山谷捷\n",
        "- 云汉芯城\n",
        "- 赛分科技\n",
        "- 影石创新\n",
        "- 三协电机\n",
        "- 星图测控\n",
        "\n",
        "核心规则：\n",
        "1. 标题必须包含“招股说明书”。\n",
        "2. 排除“申报稿”“注册稿”“提示性公告”等非正式文件。\n",
        "3. 文件大小建议大于 1MB。\n",
        "4. PDF 页数建议大于等于 200 页。\n",
        "5. 下载结果写入 `logs/download_log.csv`。"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Note: you may need to restart the kernel to use updated packages.\n"
          ]
        }
      ],
      "source": [
        "# 如本机未安装依赖，请先运行本单元。\n",
        "# 在 VS Code 的 Jupyter 环境中，运行后如提示重启内核，重启后继续运行下面单元。\n",
        "\n",
        "%pip install requests pandas beautifulsoup4 pypdf -q"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {},
      "outputs": [],
      "source": [
        "import os\n",
        "import re\n",
        "import time\n",
        "import random\n",
        "import datetime as dt\n",
        "from pathlib import Path\n",
        "from urllib.parse import urljoin\n",
        "\n",
        "import requests\n",
        "import pandas as pd\n",
        "from pypdf import PdfReader"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "项目根目录： C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd10-8326-af70-37054b68606d_be1c6f7e-bb6f-4c0d-b9f4-b46ea59c4535_mnt_data_week1_download_pdfs_package\n",
            "PDF保存目录： C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd10-8326-af70-37054b68606d_be1c6f7e-bb6f-4c0d-b9f4-b46ea59c4535_mnt_data_week1_download_pdfs_package\\downloads\\prospectus_pdfs\n",
            "日志文件： C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd10-8326-af70-37054b68606d_be1c6f7e-bb6f-4c0d-b9f4-b46ea59c4535_mnt_data_week1_download_pdfs_package\\logs\\download_log.csv\n"
          ]
        }
      ],
      "source": [
        "# ========== 1. 基础配置 ==========\n",
        "\n",
        "COMPANIES = [\n",
        "    \"三联锻造\",\n",
        "    \"友升股份\",\n",
        "    \"黄山谷捷\",\n",
        "    \"云汉芯城\",\n",
        "    \"赛分科技\",\n",
        "    \"影石创新\",\n",
        "    \"三协电机\",\n",
        "    \"星图测控\",\n",
        "]\n",
        "\n",
        "# 说明：假设 Notebook 位于 code/03_download_pdfs/ 下。\n",
        "# 在 VS Code 中打开项目根目录后运行，日志会写到 项目根目录/logs/download_log.csv。\n",
        "NOTEBOOK_DIR = Path.cwd().resolve()\n",
        "if NOTEBOOK_DIR.name == \"03_download_pdfs\":\n",
        "    PROJECT_ROOT = NOTEBOOK_DIR.parents[1]\n",
        "else:\n",
        "    PROJECT_ROOT = NOTEBOOK_DIR\n",
        "\n",
        "PDF_DIR = PROJECT_ROOT / \"downloads\" / \"prospectus_pdfs\"\n",
        "LOG_DIR = PROJECT_ROOT / \"logs\"\n",
        "PDF_DIR.mkdir(parents=True, exist_ok=True)\n",
        "LOG_DIR.mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "LOG_FILE = LOG_DIR / \"download_log.csv\"\n",
        "\n",
        "REQUIRED_KEYWORDS = [\"招股说明书\"]\n",
        "\n",
        "EXCLUDE_KEYWORDS = [\n",
        "    \"申报稿\",\n",
        "    \"注册稿\",\n",
        "    \"提示性公告\",\n",
        "    \"摘要\",\n",
        "    \"预披露\",\n",
        "    \"反馈意见\",\n",
        "    \"问询函\",\n",
        "    \"回复\",\n",
        "    \"补充法律意见书\",\n",
        "    \"上市保荐书\",\n",
        "    \"发行保荐书\",\n",
        "]\n",
        "\n",
        "MIN_FILE_SIZE_MB = 1.0\n",
        "MIN_PDF_PAGES = 200\n",
        "\n",
        "HEADERS = {\n",
        "    \"User-Agent\": (\n",
        "        \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) \"\n",
        "        \"AppleWebKit/537.36 (KHTML, like Gecko) \"\n",
        "        \"Chrome/124.0.0.0 Safari/537.36\"\n",
        "    ),\n",
        "    \"Referer\": \"http://www.cninfo.com.cn/new/commonUrl?url=disclosure/list/notice\",\n",
        "}\n",
        "\n",
        "print(\"项目根目录：\", PROJECT_ROOT)\n",
        "print(\"PDF保存目录：\", PDF_DIR)\n",
        "print(\"日志文件：\", LOG_FILE)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ========== 2. 工具函数 ==========\n",
        "\n",
        "def now_str():\n",
        "    return dt.datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")\n",
        "\n",
        "\n",
        "def safe_filename(name: str) -> str:\n",
        "    \"\"\"清理文件名中的非法字符。\"\"\"\n",
        "    return re.sub(r'[\\\\/:*?\"<>|]+', \"_\", name).strip()\n",
        "\n",
        "\n",
        "def title_is_target(title: str) -> bool:\n",
        "    \"\"\"判断公告标题是否符合正式招股说明书规则。\"\"\"\n",
        "    if not title:\n",
        "        return False\n",
        "    if not all(k in title for k in REQUIRED_KEYWORDS):\n",
        "        return False\n",
        "    if any(k in title for k in EXCLUDE_KEYWORDS):\n",
        "        return False\n",
        "    return True\n",
        "\n",
        "\n",
        "def get_pdf_page_count(pdf_path: Path):\n",
        "    \"\"\"读取 PDF 页数。读取失败返回 None。\"\"\"\n",
        "    try:\n",
        "        reader = PdfReader(str(pdf_path))\n",
        "        return len(reader.pages)\n",
        "    except Exception:\n",
        "        return None\n",
        "\n",
        "\n",
        "def file_size_mb(path: Path) -> float:\n",
        "    return path.stat().st_size / 1024 / 1024\n",
        "\n",
        "\n",
        "def guess_year_from_title(title: str) -> str:\n",
        "    \"\"\"从标题中提取年份，提取不到则用当前年份。\"\"\"\n",
        "    match = re.search(r\"(20\\\\d{2})\", title or \"\")\n",
        "    return match.group(1) if match else str(dt.datetime.now().year)\n",
        "\n",
        "\n",
        "def write_log(rows):\n",
        "    df = pd.DataFrame(rows)\n",
        "    if LOG_FILE.exists():\n",
        "        old = pd.read_csv(LOG_FILE, encoding=\"utf-8-sig\")\n",
        "        df = pd.concat([old, df], ignore_index=True)\n",
        "    df.to_csv(LOG_FILE, index=False, encoding=\"utf-8-sig\")\n",
        "    return df"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ========== 3. 巨潮资讯公告检索 ==========\n",
        "# 说明：巨潮资讯网常收录 A 股公告和招股说明书，适合作为自动检索入口。\n",
        "# 若个别公司检索不到，请在 MANUAL_URLS 中补充人工确认的 PDF 直链。\n",
        "\n",
        "CNINFO_QUERY_URL = \"http://www.cninfo.com.cn/new/hisAnnouncement/query\"\n",
        "CNINFO_PDF_PREFIX = \"http://static.cninfo.com.cn/\"\n",
        "\n",
        "def search_cninfo(company: str, max_pages: int = 5) -> list[dict]:\n",
        "    \"\"\"\n",
        "    在巨潮资讯网检索公司招股说明书公告候选项。\n",
        "    返回字段：company, title, url, source, adjunct_url, announcement_time\n",
        "    \"\"\"\n",
        "    results = []\n",
        "    for page in range(1, max_pages + 1):\n",
        "        data = {\n",
        "            \"pageNum\": page,\n",
        "            \"pageSize\": 30,\n",
        "            \"column\": \"szse\",\n",
        "            \"tabName\": \"fulltext\",\n",
        "            \"plate\": \"\",\n",
        "            \"stock\": \"\",\n",
        "            \"searchkey\": f\"{company} 招股说明书\",\n",
        "            \"secid\": \"\",\n",
        "            \"category\": \"\",\n",
        "            \"trade\": \"\",\n",
        "            \"seDate\": \"\",\n",
        "            \"sortName\": \"\",\n",
        "            \"sortType\": \"\",\n",
        "            \"isHLtitle\": \"true\",\n",
        "        }\n",
        "        try:\n",
        "            resp = requests.post(CNINFO_QUERY_URL, data=data, headers=HEADERS, timeout=20)\n",
        "            resp.raise_for_status()\n",
        "            payload = resp.json()\n",
        "        except Exception as e:\n",
        "            print(f\"[{company}] 巨潮检索失败：{e}\")\n",
        "            break\n",
        "\n",
        "        announcements = payload.get(\"announcements\") or []\n",
        "        if not announcements:\n",
        "            break\n",
        "\n",
        "        for item in announcements:\n",
        "            title = re.sub(r\"<.*?>\", \"\", item.get(\"announcementTitle\", \"\")).strip()\n",
        "            adjunct_url = item.get(\"adjunctUrl\", \"\")\n",
        "            if not adjunct_url:\n",
        "                continue\n",
        "            pdf_url = urljoin(CNINFO_PDF_PREFIX, adjunct_url)\n",
        "            results.append({\n",
        "                \"company\": company,\n",
        "                \"title\": title,\n",
        "                \"url\": pdf_url,\n",
        "                \"source\": \"cninfo\",\n",
        "                \"adjunct_url\": adjunct_url,\n",
        "                \"announcement_time\": item.get(\"announcementTime\", \"\"),\n",
        "            })\n",
        "\n",
        "        time.sleep(random.uniform(1, 3))\n",
        "    return results\n",
        "\n",
        "\n",
        "def choose_best_candidate(candidates: list[dict]):\n",
        "    \"\"\"\n",
        "    优先选择标题符合正式招股说明书规则的候选项。\n",
        "    若有多个，优先选择公告时间较新的。\n",
        "    \"\"\"\n",
        "    targets = [c for c in candidates if title_is_target(c.get(\"title\", \"\"))]\n",
        "    if not targets:\n",
        "        return None\n",
        "    targets.sort(key=lambda x: str(x.get(\"announcement_time\", \"\")), reverse=True)\n",
        "    return targets[0]"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ========== 4. 人工补充 URL 区 ==========\n",
        "# 如果自动检索失败，可把人工确认的 PDF 直链填到这里。\n",
        "# 格式示例：\n",
        "# MANUAL_URLS = {\n",
        "#     \"天和磁材\": \"https://example.com/xxx.pdf\",\n",
        "# }\n",
        "\n",
        "MANUAL_URLS = {\n",
        "    # \"三联锻造\": \"\",\n",
        "    # \"友升股份\": \"\",\n",
        "    # \"黄山谷捷\": \"\",\n",
        "    # \"云汉芯城\": \"\",\n",
        "    # \"赛分科技\": \"\",\n",
        "    # \"影石创新\": \"\",\n",
        "    # \"三协电机\": \"\",\n",
        "    # \"星图测控\": \"\",\n",
        "}"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 7,
      "metadata": {},
      "outputs": [],
      "source": [
        "# ========== 5. 下载与校验 ==========\n",
        "\n",
        "def download_pdf(url: str, save_path: Path) -> tuple[bool, str]:\n",
        "    \"\"\"下载 PDF。返回 (是否成功, 错误信息)。\"\"\"\n",
        "    try:\n",
        "        with requests.get(url, headers=HEADERS, timeout=60, stream=True) as r:\n",
        "            r.raise_for_status()\n",
        "\n",
        "            with open(save_path, \"wb\") as f:\n",
        "                for chunk in r.iter_content(chunk_size=1024 * 128):\n",
        "                    if chunk:\n",
        "                        f.write(chunk)\n",
        "\n",
        "        if not save_path.exists() or save_path.stat().st_size == 0:\n",
        "            return False, \"下载后文件不存在或为空\"\n",
        "\n",
        "        with open(save_path, \"rb\") as f:\n",
        "            head = f.read(5)\n",
        "        if head != b\"%PDF-\":\n",
        "            return False, \"文件头不是 PDF，可能下载到了网页或错误页面\"\n",
        "\n",
        "        return True, \"\"\n",
        "    except Exception as e:\n",
        "        return False, str(e)\n",
        "\n",
        "\n",
        "def download_one_company(company: str) -> dict:\n",
        "    start_time = now_str()\n",
        "\n",
        "    candidates = search_cninfo(company)\n",
        "    candidate = choose_best_candidate(candidates)\n",
        "\n",
        "    if not candidate and company in MANUAL_URLS and MANUAL_URLS[company]:\n",
        "        candidate = {\n",
        "            \"company\": company,\n",
        "            \"title\": f\"{company}_人工补充_招股说明书\",\n",
        "            \"url\": MANUAL_URLS[company],\n",
        "            \"source\": \"manual_url\",\n",
        "            \"announcement_time\": \"\",\n",
        "        }\n",
        "\n",
        "    if not candidate:\n",
        "        return {\n",
        "            \"company\": company,\n",
        "            \"status\": \"failed\",\n",
        "            \"start_time\": start_time,\n",
        "            \"end_time\": now_str(),\n",
        "            \"source\": \"\",\n",
        "            \"title\": \"\",\n",
        "            \"download_url\": \"\",\n",
        "            \"pdf_path\": \"\",\n",
        "            \"file_size_mb\": \"\",\n",
        "            \"page_count\": \"\",\n",
        "            \"passed_size_rule\": False,\n",
        "            \"passed_page_rule\": False,\n",
        "            \"error\": \"未检索到符合关键词过滤规则的正式招股说明书候选文件\",\n",
        "        }\n",
        "\n",
        "    title = candidate[\"title\"]\n",
        "    year = guess_year_from_title(title)\n",
        "    filename = safe_filename(f\"{company}_招股说明书_{year}.pdf\")\n",
        "    save_path = PDF_DIR / filename\n",
        "\n",
        "    ok, err = download_pdf(candidate[\"url\"], save_path)\n",
        "\n",
        "    if not ok:\n",
        "        if save_path.exists():\n",
        "            try:\n",
        "                save_path.unlink()\n",
        "            except Exception:\n",
        "                pass\n",
        "        return {\n",
        "            \"company\": company,\n",
        "            \"status\": \"failed\",\n",
        "            \"start_time\": start_time,\n",
        "            \"end_time\": now_str(),\n",
        "            \"source\": candidate.get(\"source\", \"\"),\n",
        "            \"title\": title,\n",
        "            \"download_url\": candidate[\"url\"],\n",
        "            \"pdf_path\": str(save_path),\n",
        "            \"file_size_mb\": \"\",\n",
        "            \"page_count\": \"\",\n",
        "            \"passed_size_rule\": False,\n",
        "            \"passed_page_rule\": False,\n",
        "            \"error\": err,\n",
        "        }\n",
        "\n",
        "    size = round(file_size_mb(save_path), 2)\n",
        "    pages = get_pdf_page_count(save_path)\n",
        "    passed_size = size >= MIN_FILE_SIZE_MB\n",
        "    passed_page = pages is not None and pages >= MIN_PDF_PAGES\n",
        "\n",
        "    if not passed_size or not passed_page:\n",
        "        status = \"downloaded_but_failed_rule_check\"\n",
        "        error = f\"规则校验未通过：文件大小={size}MB，页数={pages}\"\n",
        "    else:\n",
        "        status = \"success\"\n",
        "        error = \"\"\n",
        "\n",
        "    return {\n",
        "        \"company\": company,\n",
        "        \"status\": status,\n",
        "        \"start_time\": start_time,\n",
        "        \"end_time\": now_str(),\n",
        "        \"source\": candidate.get(\"source\", \"\"),\n",
        "        \"title\": title,\n",
        "        \"download_url\": candidate[\"url\"],\n",
        "        \"pdf_path\": str(save_path),\n",
        "        \"file_size_mb\": size,\n",
        "        \"page_count\": pages,\n",
        "        \"passed_size_rule\": passed_size,\n",
        "        \"passed_page_rule\": passed_page,\n",
        "        \"error\": error,\n",
        "    }"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 8,
      "id": "42df611a",
      "metadata": {},
      "outputs": [
        {
          "data": {
            "text/plain": [
              "{'company': '影石创新',\n",
              " 'status': 'success',\n",
              " 'start_time': '2026-06-04 16:15:52',\n",
              " 'end_time': '2026-06-04 16:15:57',\n",
              " 'source': 'cninfo',\n",
              " 'title': '影石创新首次公开发行股票并在科创板上市招股说明书',\n",
              " 'download_url': 'http://static.cninfo.com.cn/finalpage/2025-06-06/1223788474.PDF',\n",
              " 'pdf_path': 'C:\\\\Users\\\\lenovo\\\\Desktop\\\\saasnexus-6a204b3a-bd10-8326-af70-37054b68606d_be1c6f7e-bb6f-4c0d-b9f4-b46ea59c4535_mnt_data_week1_download_pdfs_package\\\\downloads\\\\prospectus_pdfs\\\\影石创新_招股说明书_2026.pdf',\n",
              " 'file_size_mb': 9.58,\n",
              " 'page_count': 555,\n",
              " 'passed_size_rule': True,\n",
              " 'passed_page_rule': True,\n",
              " 'error': ''}"
            ]
          },
          "execution_count": 8,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "row = download_one_company(\"影石创新\")\n",
        "row"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 9,
      "metadata": {},
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "开始处理：三联锻造\n",
            "完成：三联锻造 -> success\n",
            "开始处理：友升股份\n",
            "完成：友升股份 -> success\n",
            "开始处理：黄山谷捷\n",
            "完成：黄山谷捷 -> success\n",
            "开始处理：云汉芯城\n",
            "完成：云汉芯城 -> success\n",
            "开始处理：赛分科技\n",
            "完成：赛分科技 -> success\n",
            "开始处理：影石创新\n",
            "完成：影石创新 -> success\n",
            "开始处理：三协电机\n",
            "完成：三协电机 -> success\n",
            "开始处理：星图测控\n",
            "完成：星图测控 -> success\n"
          ]
        },
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>company</th>\n",
              "      <th>status</th>\n",
              "      <th>start_time</th>\n",
              "      <th>end_time</th>\n",
              "      <th>source</th>\n",
              "      <th>title</th>\n",
              "      <th>download_url</th>\n",
              "      <th>pdf_path</th>\n",
              "      <th>file_size_mb</th>\n",
              "      <th>page_count</th>\n",
              "      <th>passed_size_rule</th>\n",
              "      <th>passed_page_rule</th>\n",
              "      <th>error</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>三联锻造</td>\n",
              "      <td>success</td>\n",
              "      <td>2026-06-04 16:23:43</td>\n",
              "      <td>2026-06-04 16:23:48</td>\n",
              "      <td>cninfo</td>\n",
              "      <td>三联锻造首次公开发行股票并在主板上市招股说明书</td>\n",
              "      <td>http://static.cninfo.com.cn/finalpage/2024-12-...</td>\n",
              "      <td>C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...</td>\n",
              "      <td>7.48</td>\n",
              "      <td>564</td>\n",
              "      <td>True</td>\n",
              "      <td>True</td>\n",
              "      <td></td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>友升股份</td>\n",
              "      <td>success</td>\n",
              "      <td>2026-06-04 16:23:50</td>\n",
              "      <td>2026-06-04 16:23:53</td>\n",
              "      <td>cninfo</td>\n",
              "      <td>友升股份首次公开发行股票并在主板上市招股说明书</td>\n",
              "      <td>http://static.cninfo.com.cn/finalpage/2025-09-...</td>\n",
              "      <td>C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...</td>\n",
              "      <td>5.72</td>\n",
              "      <td>398</td>\n",
              "      <td>True</td>\n",
              "      <td>True</td>\n",
              "      <td></td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>黄山谷捷</td>\n",
              "      <td>success</td>\n",
              "      <td>2026-06-04 16:23:56</td>\n",
              "      <td>2026-06-04 16:24:05</td>\n",
              "      <td>cninfo</td>\n",
              "      <td>首次公开发行股票并在创业板上市招股说明书</td>\n",
              "      <td>http://static.cninfo.com.cn/finalpage/2024-12-...</td>\n",
              "      <td>C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...</td>\n",
              "      <td>5.44</td>\n",
              "      <td>343</td>\n",
              "      <td>True</td>\n",
              "      <td>True</td>\n",
              "      <td></td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>云汉芯城</td>\n",
              "      <td>success</td>\n",
              "      <td>2026-06-04 16:24:07</td>\n",
              "      <td>2026-06-04 16:24:11</td>\n",
              "      <td>cninfo</td>\n",
              "      <td>首次公开发行股票并在创业板上市招股说明书</td>\n",
              "      <td>http://static.cninfo.com.cn/finalpage/2025-09-...</td>\n",
              "      <td>C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...</td>\n",
              "      <td>10.89</td>\n",
              "      <td>443</td>\n",
              "      <td>True</td>\n",
              "      <td>True</td>\n",
              "      <td></td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>赛分科技</td>\n",
              "      <td>success</td>\n",
              "      <td>2026-06-04 16:24:12</td>\n",
              "      <td>2026-06-04 16:24:17</td>\n",
              "      <td>cninfo</td>\n",
              "      <td>赛分科技首次公开发行股票并在科创板上市招股说明书</td>\n",
              "      <td>http://static.cninfo.com.cn/finalpage/2025-01-...</td>\n",
              "      <td>C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...</td>\n",
              "      <td>8.09</td>\n",
              "      <td>468</td>\n",
              "      <td>True</td>\n",
              "      <td>True</td>\n",
              "      <td></td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>影石创新</td>\n",
              "      <td>success</td>\n",
              "      <td>2026-06-04 16:24:20</td>\n",
              "      <td>2026-06-04 16:24:31</td>\n",
              "      <td>cninfo</td>\n",
              "      <td>影石创新首次公开发行股票并在科创板上市招股说明书</td>\n",
              "      <td>http://static.cninfo.com.cn/finalpage/2025-06-...</td>\n",
              "      <td>C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...</td>\n",
              "      <td>9.58</td>\n",
              "      <td>555</td>\n",
              "      <td>True</td>\n",
              "      <td>True</td>\n",
              "      <td></td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>三协电机</td>\n",
              "      <td>success</td>\n",
              "      <td>2026-06-04 16:24:33</td>\n",
              "      <td>2026-06-04 16:24:37</td>\n",
              "      <td>cninfo</td>\n",
              "      <td>招股说明书</td>\n",
              "      <td>http://static.cninfo.com.cn/finalpage/2025-08-...</td>\n",
              "      <td>C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...</td>\n",
              "      <td>6.10</td>\n",
              "      <td>382</td>\n",
              "      <td>True</td>\n",
              "      <td>True</td>\n",
              "      <td></td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>星图测控</td>\n",
              "      <td>success</td>\n",
              "      <td>2026-06-04 16:24:39</td>\n",
              "      <td>2026-06-04 16:24:44</td>\n",
              "      <td>cninfo</td>\n",
              "      <td>招股说明书</td>\n",
              "      <td>http://static.cninfo.com.cn/finalpage/2025-11-...</td>\n",
              "      <td>C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...</td>\n",
              "      <td>6.76</td>\n",
              "      <td>391</td>\n",
              "      <td>True</td>\n",
              "      <td>True</td>\n",
              "      <td></td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "  company   status           start_time             end_time  source  \\\n",
              "0    三联锻造  success  2026-06-04 16:23:43  2026-06-04 16:23:48  cninfo   \n",
              "1    友升股份  success  2026-06-04 16:23:50  2026-06-04 16:23:53  cninfo   \n",
              "2    黄山谷捷  success  2026-06-04 16:23:56  2026-06-04 16:24:05  cninfo   \n",
              "3    云汉芯城  success  2026-06-04 16:24:07  2026-06-04 16:24:11  cninfo   \n",
              "4    赛分科技  success  2026-06-04 16:24:12  2026-06-04 16:24:17  cninfo   \n",
              "5    影石创新  success  2026-06-04 16:24:20  2026-06-04 16:24:31  cninfo   \n",
              "6    三协电机  success  2026-06-04 16:24:33  2026-06-04 16:24:37  cninfo   \n",
              "7    星图测控  success  2026-06-04 16:24:39  2026-06-04 16:24:44  cninfo   \n",
              "\n",
              "                      title  \\\n",
              "0   三联锻造首次公开发行股票并在主板上市招股说明书   \n",
              "1   友升股份首次公开发行股票并在主板上市招股说明书   \n",
              "2      首次公开发行股票并在创业板上市招股说明书   \n",
              "3      首次公开发行股票并在创业板上市招股说明书   \n",
              "4  赛分科技首次公开发行股票并在科创板上市招股说明书   \n",
              "5  影石创新首次公开发行股票并在科创板上市招股说明书   \n",
              "6                     招股说明书   \n",
              "7                     招股说明书   \n",
              "\n",
              "                                        download_url  \\\n",
              "0  http://static.cninfo.com.cn/finalpage/2024-12-...   \n",
              "1  http://static.cninfo.com.cn/finalpage/2025-09-...   \n",
              "2  http://static.cninfo.com.cn/finalpage/2024-12-...   \n",
              "3  http://static.cninfo.com.cn/finalpage/2025-09-...   \n",
              "4  http://static.cninfo.com.cn/finalpage/2025-01-...   \n",
              "5  http://static.cninfo.com.cn/finalpage/2025-06-...   \n",
              "6  http://static.cninfo.com.cn/finalpage/2025-08-...   \n",
              "7  http://static.cninfo.com.cn/finalpage/2025-11-...   \n",
              "\n",
              "                                            pdf_path  file_size_mb  \\\n",
              "0  C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...          7.48   \n",
              "1  C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...          5.72   \n",
              "2  C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...          5.44   \n",
              "3  C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...         10.89   \n",
              "4  C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...          8.09   \n",
              "5  C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...          9.58   \n",
              "6  C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...          6.10   \n",
              "7  C:\\Users\\lenovo\\Desktop\\saasnexus-6a204b3a-bd1...          6.76   \n",
              "\n",
              "   page_count  passed_size_rule  passed_page_rule error  \n",
              "0         564              True              True        \n",
              "1         398              True              True        \n",
              "2         343              True              True        \n",
              "3         443              True              True        \n",
              "4         468              True              True        \n",
              "5         555              True              True        \n",
              "6         382              True              True        \n",
              "7         391              True              True        "
            ]
          },
          "execution_count": 9,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "# ========== 6. 批量执行下载 ==========\n",
        "\n",
        "log_rows = []\n",
        "\n",
        "for company in COMPANIES:\n",
        "    print(f\"开始处理：{company}\")\n",
        "    row = download_one_company(company)\n",
        "    log_rows.append(row)\n",
        "    print(f\"完成：{company} -> {row['status']}\")\n",
        "    time.sleep(random.uniform(1, 3))\n",
        "\n",
        "download_log_df = write_log(log_rows)\n",
        "download_log_df"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 10,
      "metadata": {},
      "outputs": [
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>status</th>\n",
              "      <th>count</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>success</td>\n",
              "      <td>8</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "    status  count\n",
              "0  success      8"
            ]
          },
          "execution_count": 10,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "# ========== 7. 查看本轮下载结果 ==========\n",
        "\n",
        "latest = pd.DataFrame(log_rows)\n",
        "summary = latest.groupby(\"status\").size().reset_index(name=\"count\")\n",
        "summary"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 11,
      "metadata": {},
      "outputs": [
        {
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>company</th>\n",
              "      <th>status</th>\n",
              "      <th>start_time</th>\n",
              "      <th>end_time</th>\n",
              "      <th>source</th>\n",
              "      <th>title</th>\n",
              "      <th>download_url</th>\n",
              "      <th>pdf_path</th>\n",
              "      <th>file_size_mb</th>\n",
              "      <th>page_count</th>\n",
              "      <th>passed_size_rule</th>\n",
              "      <th>passed_page_rule</th>\n",
              "      <th>error</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "Empty DataFrame\n",
              "Columns: [company, status, start_time, end_time, source, title, download_url, pdf_path, file_size_mb, page_count, passed_size_rule, passed_page_rule, error]\n",
              "Index: []"
            ]
          },
          "execution_count": 11,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "# ========== 8. 查看失败或规则未通过样本 ==========\n",
        "\n",
        "latest[latest[\"status\"] != \"success\"]"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "base",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.13.13"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}
